version: '1'

services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:latest
    container_name: weaviate
    hostname: weaviate
    ports:
    - 8080:8080
    - 50051:50051
    restart: on-failure:0
    volumes:
    - ./weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      CLUSTER_HOSTNAME: 'node1'
      MODULES_CLIENT_TIMEOUT: 5m

  ollama:
    image: ollama/ollama:0.1.42
    container_name: ollama
    hostname: ollama
    ports:
      - 11434:11434
    restart: always
    volumes:
      - ./ollama:/root/.ollama
      
  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: webui
    hostname: webui
    ports:
      - 8081:8080
    depends_on:
      - ollama
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    volumes:
      - ./webui:/app/backend/data
